// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbxzzudqfyilqhamztvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNieHp6dWRxZnlpbHFoYW16dHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDI2MTksImV4cCI6MjA2NjE3ODYxOX0.ZG95d4eitndpkO7XiH1Llfc4oUrJBBfRnQz7AEXvy_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});